package lu.uni.lassy.excalibur.examples.icrash.dev.web.java.views.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Slider;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ActivatorDesign extends VerticalLayout {
	protected Label welcomeText;
	protected Panel contentPanel;
	protected GridLayout gridLayout;
	protected Label dateText;
	protected PopupDateField date;
	protected Button nowBtn;
	protected Label hourText;
	protected Slider hourSlider;
	protected TextField inputHour;
	protected Label minuteText;
	protected Slider minuteSlider;
	protected TextField inputMinute;
	protected Label secondText;
	protected Slider secondSlider;
	protected TextField inputSecond;
	protected Button setTimeBtn;

	public ActivatorDesign() {
		Design.read(this);
	}
}
