package lu.uni.lassy.excalibur.examples.icrash.dev.web.java.views.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Slider;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ComCompanyDesign extends VerticalLayout {
	protected VerticalLayout headerlayout;
	protected Label welcomeText;
	protected Label comCompanyNameToShow;
	protected HorizontalLayout externalContentLayout;
	protected Panel bigContentPanel;
	protected VerticalLayout bigPanelLayout;
	protected VerticalLayout typeOfPersonLayout;
	protected ComboBox typeOfPerson;
	protected VerticalLayout panelLayout;
	protected VerticalLayout dataLayout;
	protected TextField phoneNr;
	protected TextField latitude;
	protected TextField longitude;
	protected TextArea comment;
	protected VerticalLayout dateTimeLayout;
	protected DateField date;
	protected GridLayout timeLayout;
	protected Slider hourSlider;
	protected TextField inputHour;
	protected Slider minuteSlider;
	protected TextField inputMinute;
	protected Slider secondSlider;
	protected TextField inputSecond;
	protected Button sendAlertBtn;
	protected Panel messagesPanel;
	protected Table comCompanyMessages;

	public ComCompanyDesign() {
		Design.read(this);
	}
}
